environment: development
etl_paths:
  data_root: data
  assembly:
    base: assembly
    temp_formatted: assembly/temp/formatted
    temp_raw: assembly/temp/raw
    ref: assembly/ref
    raw: assembly/raw
    formatted: assembly/formatted
  document:
    text: document/text
    pdf: document/pdf
    parsed: document/parsed
  law:
    raw: law/raw
