environment: development
etl_paths:
  data_root: data
  assembly:
    temp_raw: assembly/temp/raw
    temp_formatted: assembly/temp/formatted
    ref: assembly/ref
    raw: assembly/raw
    formatted: assembly/formatted
  document:
    text: document/temp/text
    pdf: document/temp/pdf
    parsed: document/temp/parsed
  law:
    raw: law/raw
